name: Continuos deployment

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
    branches: [main]
  
  push:
    branches: [main]

concurrency:
  group: staging-merge-${{ github.event.pull_request.number }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  merge-to-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: read
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge approved PR to staging
        id: merge
        uses: docker://ghcr.io/josedpiambav/feature:latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          trunk_branch: "main"
          labels: "next-feature"
